<?php

/**
 * @file gnl_api.module
 */

define("GNL_API_DEFAULT_LIMIT", 10);
define("GNL_API_MAX_LIMIT", 100);

/**
 * Implementats hook_services_resources().
 */
function gnl_api_services_resources() {
  $api = array(
    'org' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Retrieves a single Organization',
          'callback' => '_gnl_api_get_org',
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'org_id',
              'type' => 'string',
              'description' => 'Organization ID',
              'source' => array('path' => '1'),
              'optional' => TRUE,
              'default' => '0',
            ),
          ),
        ),
      ),
    ),
    'orgs' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Retrieves Organizations',
          'callback' => '_gnl_api_get_orgs',
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'limit',
              'type' => 'int',
              'description' => 'Limit response count, default 10',
              'source' => array('param' => 'limit'),
              'optional' => TRUE,
              'default' => GNL_API_DEFAULT_LIMIT,
            ),
            array(
              'name' => 'offset',
              'type' => 'int',
              'description' => 'Offset starting record',
              'source' => array('param' => 'offset'),
              'optional' => TRUE,
              'default' => 0,
            ),
          ),
        ),
      ),
    ),
  );

  return $api;
}

function _gnl_api_get_org($org_id) {
  return node_load($org_id);
}

function _gnl_api_get_orgs($limit, $offset) {
  $limit = (is_int($limit) && $limit < GNL_API_MAX_LIMIT) ? $limit : GNL_API_DEFAULT_LIMIT;
  $offset = (is_int($offset)) ? $offset : 0;

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'org')
    ->propertyCondition('status', 1)
    ->propertyOrderBy('created', 'ASC')
    ->range($offset, $limit)
    ->addMetaData('account', user_load(1));

  $res = $query->execute();
  $org_nids = array_keys($res['node']);

  $orgs = node_load_multiple($org_nids);

  return $orgs;
}

function _gnl_api_get_grant($grant_id) {

}

function _gnl_api_get_grants($limit) {

}
