<?php
/**
 * @file
 * Code for the gnl_schema feature.
 */

include_once 'gnl_schema.features.inc';

/**
 * Implements hook_entity_info_alter().
 *
 * Add view modes.
 */
function gnl_schema_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['grantor_only'] = array(
    'label' => t('Grantor only'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['grantee_only'] = array(
    'label' => t('Grantee only'),
    'custom settings' => FALSE,
  );
}

/**
* Implements hook_preprocess_node().
*
* Add template hints for the added view modes
*/
function gnl_schema_preprocess_node(&$vars) {
  if($vars['view_mode'] == 'grantor_only') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__grantor_only';
  }
  if($vars['view_mode'] == 'grantee_only') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__grantee_only';
  }
}

/**
 * Implements hook_form_alter().
 *
 * Dupe some fields from the previously-added grant.
 */
function gnl_schema_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'grant_node_form') {
    $q = new EntityFieldQuery();
    $q->entityCondition('entity_type', 'node')
      ->propertyCondition('type', 'grant')
      ->range(0, 1)
      ->propertyOrderBy('changed', 'DESC');
    $res = $q->execute();
    $node = node_load(current(array_keys($res['node'])));
    $mru = entity_metadata_wrapper('node', $node);
    $mru_dates = $mru->field_year->value();
    $form['field_year'][LANGUAGE_NONE][0]['#default_value']['value'] = $mru_dates['value'];
    $form['field_year'][LANGUAGE_NONE][0]['#default_value']['value2'] = $mru_dates['value2'];
    $form['field_source'][LANGUAGE_NONE][0]['value']['#default_value'] = $mru->field_source->value();
    // kludge-ville USA: https://drupal.org/node/1514444
    $form['field_funder'][LANGUAGE_NONE][0]['target_id']['#default_value'] = $mru->field_funder->value()->title . " (" . $mru->field_funder->value()->nid . ")";
  }
}

